language: generic
dist: trusty

install:
  - openssl aes-256-cbc -K $encrypted_73f414ac1fc7_key -iv $encrypted_73f414ac1fc7_iv -in .travis_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.name garario3
  - git config --global user.email garario3@gmail.com

  - git remote -v
  - git remote set-url origin git@github.com:conao3/feather-melpa.git

branches:
  only:
    - master

script:
  - make fetch
  - make merge-upstream
  - make checkout
  - make html/recipes.json
  - make html-stable/recipes.json

after_success:
  - make commit-json && make merge-travis && make push
